name = "cannon-example"
description = "Some cannon example"
version = "0.0.1"

[import.dai]
source = "erc20:0.2.3"
options.name = "Maker DAI"
options.symbol = "DAI"

[import.usdc]
source = "erc20:0.2.3"
options.name = "USD Coin"
options.symbol = "USDC"

[invoke.mint_dai]
addresses = ["<%= outputs.dai.contracts.erc20.address %>"]
abi = "<%= outputs.dai.contracts.erc20.abi %>"
func = "mint"
args = [5000]
step = 4

[invoke.mint_usdc]
addresses = ["<%= outputs.usdc.contracts.erc20.address %>"]
abi = "<%= outputs.usdc.contracts.erc20.abi %>"
func = "mint"
args = [5000]
step = 4
